---
- name: create flannel group
  become: yes
  become_user: root
  group:
    name: '{{flannel_group}}'
    state: present
  
- name: create flannel user
  become: yes
  become_user: root
  user:
    name: '{{flannel_user}}'
    group: '{{flannel_group}}'
    home: '{{flannel_data_dir}}'
    state: present

- name: create dirs...
  become: yes
  become_user: root
  with_items:
    - '{{flannel_conf_dir}}'
    - '{{flannel_cluster_pki_dir}}'
    - '{{flannel_run_dir}}'
  file:
    state: directory
    path: '{{item}}'
    owner: '{{flannel_user}}'
    group: '{{flannel_group}}'
    mode: '0755'

- include: pki.yml
    
- name: configurate flannel...
  become: yes
  become_user: root
  with_items:
    - options.env
  template:
    src: '{{item}}.j2'
    dest: '{{flannel_conf_dir}}/{{item}}'
    owner: '{{flannel_user}}'
    group: '{{flannel_group}}'
    mode: '0644'

- include: '{{flannel_init_system|default("systemd")}}.yml'
