---
- name: install keys/certs
  when: flannel_secure
  become: yes
  become_user: root
  with_items:
    - { f: '{{flannel_pki_key_src}}', d: '{{flannel_pki_key_dest}}', m: '0400' }
    - { f: '{{flannel_pki_cert_src}}', d: '{{flannel_pki_cert_dest}}', m: '0600'}
    - { f: '{{flannel_pki_ca_cert_src}}', d: '{{flannel_pki_ca_cert_dest}}', m: '0600' }
  copy:
    src: '{{item.f}}'
    dest: '{{item.d}}'
    owner: '{{flannel_user}}'
    group: '{{flannel_group}}'
    mode: '{{item.m}}'

