---
- name: install flannel.service...
  become: yes
  become_user: root
  register: flannel_service_modified
  with_items:
    - f: flanneld.service
      d: /etc/systemd/system
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: flannel_service_modified is changed and flannel_launch
  systemd:
    daemon_reload: yes

- name: start flannel...
  when: flannel_launch
  become: yes
  become_user: root
  service:
    name: flanneld
    enabled: yes
    state: started
