---
    
- name: install flannel.service systemd unit
  become: yes
  become_user: root
  register: flannel_service_modified
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0644
  with_items:
    - etc/systemd/system/flanneld.service

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: flannel_service_modified|changed
  command: systemctl daemon-reload
    
- name: start_flannel 
  when: flannel_launch
  become: yes
  become_user: root
  service: name=flanneld enabled=yes state=started
