---
- name: install flannel.service...
  become: yes
  become_user: root
  register: flannel_service_modified
  with_items:
    - flanneld.service
  template:
    src: '{{item}}.j2'
    dest: /etc/systemd/system/{{item}}
    mode: '0644'

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: flannel_service_modified|changed and flannel_launch
  command: systemctl daemon-reload
    
- name: start flannel...
  when: flannel_launch
  become: yes
  become_user: root
  service:
    name: flanneld
    enabled: yes
    state: started
